#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SYMBOL_TABLE_SIZE 1024
#define MAX_IDENTIFIER_SIZE 64
#define MAX_ARGUMENT_NUMBER 32

#define MAX_CODE_GEN_LINE_SIZE 256
#define MAX_CODE_GEN_LINE_NUMBER 2048
#define MAX_GUARD_LINE_NUMBER 64

#endif
